### PR TITLE
Make logger level writes/reads thread safe

### PR DESCRIPTION
**Pull request by kuujo**
Fixes thread safety issues in loggers.

### CODE REVIEW

**Comment by kuujo** [comment]
Actually, I think this should be done

**Comment by kuujo** [comment]
I changed it to use atomic value rather than locks for the levels. That eliminates any contention issues and just changes how the levels are read.

**Comment by adibrastegarnia** [comment]
> Do we anticipate any noticeable performance impact? I mean, I know the correctness > performance, but just asking. :)

Independent of the locks, we use sugared logger right now but we should support default Zap logger as well which is much faster to have this capability to switch to that logger whenever is needed. 
Based on Zap documents: When performance and type safety are critical, use the Logger. It's even faster than the SugaredLogger and allocates far less, but it only supports structured logging.

**Comment by kuujo** [comment]
Now the lock is only used when `GetLogger` is called. When level is written/read, it just uses `atomic.Value`.

**Pull request merged**
